import { getDatabase } from '../db/connection.js';
import { logger } from '../utils/logger.js';
import { writeFile } from './fileManager.js';
import path from 'path';
import { config } from '../config/index.js';

/**
 * Generate a markdown table of environment variables.
 * @param {{name: string, value: string, description: string|null}[]} envVars
 * @returns {string}
 */
function generateEnvTable(envVars) {
  if (!envVars || envVars.length === 0) {
    return '_No environment variables configured._\n';
  }

  const rows = envVars.map(v => {
    const desc = v.description ? v.description.replace(/\|/g, '\\|') : '';
    return `| ${v.name} | \`${'*'.repeat(Math.min(v.value.length, 8))}\` | ${desc} |`;
  });

  return [
    '| Variable | Value | Description |',
    '|----------|-------|-------------|',
    ...rows,
    '',
  ].join('\n');
}

/**
 * Generate a skills section.
 * @param {{name: string, description: string|null, path: string}[]} skills
 * @returns {string}
 */
function generateSkillsSection(skills) {
  if (!skills || skills.length === 0) {
    return '_No skills linked._\n';
  }

  return skills.map(s => {
    const desc = s.description || '';
    return `- **${s.name}**: ${desc}`;
  }).join('\n') + '\n';
}

/**
 * Sanitize a service name for safe file path usage.
 * @param {string} serviceName
 * @returns {string}
 */
function sanitizeServiceName(serviceName) {
  if (!serviceName || typeof serviceName !== 'string') {
    return 'unnamed-service';
  }

  // Remove directory traversal sequences and only allow safe characters
  return serviceName
    .replace(/[\.\/\\]/g, '') // Remove dots, slashes, backslashes
    .replace(/[^a-zA-Z0-9_-]/g, '_') // Replace other unsafe chars with underscores
    .substring(0, 100) // Limit length
    .trim();
}

/**
 * Generate a README.md for a service.
 * @param {number} serviceId
 * @returns {Promise<{success: boolean, message: string, content: string|null}>}
 */
export async function generateServiceReadme(serviceId) {
  const db = getDatabase();
  const service = db.prepare('SELECT * FROM services WHERE id = ?').get(serviceId);

  if (!service) {
    return { success: false, message: 'Service not found', content: null };
  }

  // Get linked env vars
  const envVars = db.prepare(`
    SELECT name, value, description FROM env_vars WHERE service_name = ? ORDER BY name
  `).all(service.name);

  // Get linked skills
  const skills = db.prepare(`
    SELECT s.name, s.description, s.path
    FROM skills s
    INNER JOIN env_vars ev ON ev.skill_id = s.id
    WHERE ev.service_name = ?
    GROUP BY s.id
  `).all(service.name);

  const now = new Date().toISOString();

  const content = `# ${service.name}

${service.description || '_No description provided._'}

> Auto-generated by OpenClaw Secure Vault on ${now}

## Table of Contents

- [Environment Variables](#environment-variables)
- [Skills](#skills)
- [API Documentation](#api-documentation)

---

## Environment Variables

${generateEnvTable(envVars)}

## Skills

${generateSkillsSection(skills)}

## API Documentation

${service.swagger_url ? `[Swagger UI](${service.swagger_url})` : '_No Swagger URL configured._'}

---

*This README was automatically generated. Do not edit manually — changes will be overwritten.*
`;

  try {
    // Sanitize the service name to prevent path traversal
    const safeServiceName = sanitizeServiceName(service.name);
    const filePath = path.join(config.paths.servicesDir, `${safeServiceName}.md`);
    
    // Verify the resolved path is within the intended directory
    const resolvedPath = path.resolve(filePath);
    const expectedDir = path.resolve(config.paths.servicesDir);
    if (!resolvedPath.startsWith(expectedDir + path.sep)) {
      throw new Error('Invalid file path: potential directory traversal detected');
    }
    
    writeFile(filePath, content);
    logger.info({ serviceId, path: filePath }, 'README generated');
    return { success: true, message: 'README generated successfully', content };
  } catch (error) {
    logger.error({ error, serviceId }, 'README generation failed');
    return { success: false, message: error.message, content: null };
  }
}

/**
 * Generate a master README for the entire vault.
 * @returns {Promise<{success: boolean, message: string, content: string|null}>}
 */
export async function generateVaultReadme() {
  const db = getDatabase();
  const services = db.prepare('SELECT * FROM services ORDER BY name').all();
  const envCount = db.prepare('SELECT COUNT(*) as count FROM env_vars').get();
  const skillCount = db.prepare('SELECT COUNT(*) as count FROM skills').get();

  const serviceList = services.map(s => `- [${s.name}](services/${s.name}.md) — ${s.description || ''}`).join('\n');

  const content = `# OpenClaw Secure Vault

> Master documentation — ${new Date().toISOString()}

## Overview

| Metric | Count |
|--------|-------|
| Services | ${services.length} |
| Environment Variables | ${envCount.count} |
| Skills | ${skillCount.count} |

## Services

${serviceList || '_No services registered._'}

---

*This README was automatically generated by OpenClaw Secure Vault.*
`;

  try {
    writeFile('README.md', content);
    return { success: true, message: 'Vault README generated', content };
  } catch (error) {
    return { success: false, message: error.message, content: null };
  }
}
